import { GoogleGenerativeAI } from '@google/generative-ai';
import dotenv from 'dotenv';
dotenv.config();

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

// Helper to recursively validate MongoDB operators
function validateMongoFilter(obj) {
  const allowedOperators = ['$gt', '$gte', '$lt', '$lte', '$eq', '$ne', '$in'];
  
  if (typeof obj !== 'object' || obj === null) return;
  
  if (Array.isArray(obj)) {
    obj.forEach(validateMongoFilter);
    return;
  }

  for (const key of Object.keys(obj)) {
    if (key.startsWith('$')) {
      if (!allowedOperators.includes(key)) {
        throw new Error(`Invalid or dangerous MongoDB operator detected: ${key}`);
      }
    }
    validateMongoFilter(obj[key]);
  }
}


export async function generateMongoFilter(prompt) {
  try {
    const result = await model.generateContent(`You are an AI assistant for a CRM that converts natural language audience descriptions into MongoDB filter JSON queries.
      
Collection "Customer" Schema:
{
  name: String,
  email: String,
  phone: String,
  city: String,
  totalSpent: Number,
  orderCount: Number,
  lastOrderDate: Date,
  preferredChannel: String (WhatsApp, SMS, Email, RCS)
}

Convert the following request into a strictly valid JSON object representing a MongoDB query filter.
Do not wrap it in markdown blockquotes or add any other text. Return ONLY valid parseable JSON. Use standard MongoDB operators ($gt, $lt, $gte, etc).
Dates should be represented as strings that can be parsed, or if "last 30 days", calculate roughly (you don't have Date.now() but you can generate a $gte using an ISO date string or you can just return a placeholder that backend replaces, let's use a standard format). 
Actually, better yet, output something like {"lastOrderDate": {"$gte": "30_DAYS_AGO"}} and the backend will replace it.
Known replacements:
"30_DAYS_AGO", "60_DAYS_AGO", "90_DAYS_AGO".

User Request: "${prompt}"
`);
    
    let text = result.response.text().trim();
    if(text.startsWith('\`\`\`json')){
        text = text.substring(7);
    }
    if(text.startsWith('\`\`\`')){
        text = text.substring(3);
    }
    if(text.endsWith('\`\`\`')){
        text = text.substring(0, text.length - 3);
    }
    let parsedJson;
    try {
      parsedJson = JSON.parse(text);
      validateMongoFilter(parsedJson);
    } catch (parseError) {
      console.error("Gemini output was invalid JSON or contained dangerous operators:", text, parseError.message);
      // Fallback response for safe failure
      throw new Error("Invalid query generated by AI. Please refine your prompt.");
    }
    
    return parsedJson;
  } catch (error) {
    console.error("Gemini Error:", error);
    throw new Error(error.message || "Failed to generate filter due to AI service error.");
  }
}

export async function generateCampaignContent(segmentDescription, goal) {
  try {
    const result = await model.generateContent(`You are an AI Marketing Assistant. 
Generate a marketing campaign based on:
Audience: ${segmentDescription}
Goal: ${goal}

Provide the output as STRICTLY valid JSON with the following schema:
{
  "campaignName": "A catchy name",
  "message": "The personalized marketing message",
  "recommendedChannel": "One of: WhatsApp, SMS, Email, RCS",
  "reason": "Why you recommended this channel"
}
Do not include any other text or markdown blockquotes, just the JSON object.
`);
    let text = result.response.text().trim();
    if(text.startsWith('\`\`\`json')){
        text = text.substring(7);
    }
    if(text.startsWith('\`\`\`')){
        text = text.substring(3);
    }
    if(text.endsWith('\`\`\`')){
        text = text.substring(0, text.length - 3);
    }
    let parsedJson;
    try {
      parsedJson = JSON.parse(text);
    } catch (parseError) {
      console.error("Failed to parse campaign JSON:", text);
      return { campaignName: "Fallback Campaign", message: "Here is your fallback message.", recommendedChannel: "Email", reason: "Fallback" };
    }
    return parsedJson;
  } catch (error) {
    console.error("Gemini Error:", error);
    throw new Error("Failed to generate campaign content");
  }
}

export async function generateInsights(funnelMetrics) {
  try {
    const result = await model.generateContent(`You are an AI Data Analyst. Analyze these campaign metrics and provide 2-3 brief insights or recommendations.
Metrics: ${JSON.stringify(funnelMetrics)}
Return ONLY a JSON array of strings.`);
    let text = result.response.text().trim();
    if(text.startsWith('\`\`\`json')){
        text = text.substring(7);
    }
    if(text.startsWith('\`\`\`')){
        text = text.substring(3);
    }
    if(text.endsWith('\`\`\`')){
        text = text.substring(0, text.length - 3);
    }
    let parsedJson;
    try {
      parsedJson = JSON.parse(text);
    } catch (parseError) {
      console.error("Failed to parse insights JSON:", text);
      return ["Performance is tracking normally.", "Consider A/B testing different channels next time."];
    }
    return parsedJson;
  } catch (error) {
    return ["Performance is tracking normally.", "Consider A/B testing different channels next time."];
  }
}

export async function explainOpportunity(opportunityType, data) {
  try {
    const result = await model.generateContent(`You are an AI Marketing Strategist. 
Explain this marketing opportunity in exactly 1 short, impactful sentence.
Opportunity Type: ${opportunityType}
Data: ${JSON.stringify(data)}

Example outputs:
"247 customers have not purchased for 45 days."
"92 customers recently became high-value buyers."
"153 customers clicked a campaign but never converted."
Return ONLY the sentence.`);
    return result.response.text().trim().replace(/^["']|["']$/g, '');
  } catch (error) {
    console.error("Gemini Error:", error);
    return `${data.count} customers identified for ${opportunityType}.`;
  }
}

export async function generateCopilotCampaign(segmentName, audienceCount) {
  try {
    const result = await model.generateContent(`You are an AI Marketing Strategist. The user clicked "Generate Complete Campaign" for:
Segment: ${segmentName}
Audience Size: ${audienceCount}

Create a complete campaign. Output strictly JSON:
{
  "segmentName": "${segmentName}",
  "audienceCount": ${audienceCount},
  "campaignGoal": "Your determined goal (e.g., Win-back, Upsell)",
  "recommendedChannel": "One of: WhatsApp, SMS, Email, RCS",
  "campaignMessage": "The persuasive message copy",
  "reasoning": "Why this channel and message were chosen."
}`);
    let text = result.response.text().trim();
    if(text.startsWith('```json')) text = text.substring(7);
    if(text.startsWith('```')) text = text.substring(3);
    if(text.endsWith('```')) text = text.substring(0, text.length - 3);
    let parsedJson;
    try {
      parsedJson = JSON.parse(text);
    } catch (parseError) {
      console.error("Failed to parse copilot JSON:", text);
      return {
        segmentName,
        audienceCount,
        campaignGoal: "General Outreach",
        recommendedChannel: "Email",
        campaignMessage: "Hello! Check out our latest products.",
        reasoning: "Fallback mechanism triggered."
      };
    }
    return parsedJson;
  } catch (error) {
    console.error("Gemini Error:", error);
    throw new Error("Failed to generate copilot campaign");
  }
}
