services:
  - type: web
    name: xeno-crm-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CHANNEL_SERVICE_URL
        value: "https://xeno-crm-channel-service.onrender.com/send"
      - key: FRONTEND_URL
        value: "https://xeno-crm-frontend.vercel.app"
  
  - type: web
    name: xeno-crm-channel-service
    env: node
    rootDir: channel-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: BACKEND_RECEIPT_URL
        value: "https://xeno-crm-backend.onrender.com/receipt"
